defaults: &defaults
  read_only: false
  front_page_search_enabled: true
  elasticsearch_url: <%= ENV['ELASTICSEARCH_URL'] || ENV['BONSAI_URL'] || 'http://localhost:9200' %>
  statsd_host: 5.9.122.47 # ops1.holderdeord.no, but avoid DNS lookup
  statsd_port: 8125
  statsd_enabled: false
  analytics_enabled: false
  questions_enabled: true
  ignore_votes_against_alternate_budget: true
  ignore_votes_against_proposal_attached_to_minutes: false
  vote_scoring_bins: 3
  show_accountability: true
  widgets_enabled: true

development:
  beta?: true
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  statsd_enabled: true

production:
  <<: *defaults
  analytics_enabled: true
  questions_enabled: false
  widgets_enabled: false
